nodeLinker: node-modules

enableGlobalCache: true

nmMode: hardlinks-local

compressionLevel: mixed

enableImmutableInstalls: false

packageExtensions:
  ts-node-dev@2.0.0:
    dependencies:
      '@types/node': '*'

npmRegistryServer: "https://registry.npmjs.org"

httpTimeout: 120000

networkConcurrency: 8

enableNetwork: true
