nodeLinker: node-modules

enableGlobalCache: true

nmMode: hardlinks-local

compressionLevel: mixed

enableImmutableInstalls: false

npmRegistryServer: "https://registry.npmjs.org"

httpTimeout: 120000

networkConcurrency: 8

enableNetwork: true
